name: ECS Deploy (practice)

on:
  push:
    branches:
      - v2

env:
  AWS_REGION: "ap-northeast-1"
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ROLE_NAME: ${{ secrets.AWS_ROLE_NAME }}
  DOCKER_BUILDKIT: "1"
  APP_NAME: "sbcntr-frontend-app"
  ECS_CLUSTER: "sbcntr-app"

jobs:
  deploy:
    runs-on: ubuntu-24.04-arm

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE_NAME }}"
          aws-region: ${{ env.AWS_REGION }}

      - name: Identity Check
        run: |
          aws sts get-caller-identity > /dev/null && echo "AWS Login OK"

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set image tag
        run: |
          echo "IMAGE_TAG=$(echo ${{ github.sha }} | cut -c 1-7)" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Build and push image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          platforms: linux/arm64
          tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}
          provenance: false
          sbom: false

      - name: Download task definition
        run: |
          aws ecs describe-task-definition --task-definition ${{ env.APP_NAME }} --query taskDefinition > task-definition.json

      - name: Fill in the new image ID in the Amazon ECS task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: task-definition.json
          container-name: app
          image: ${{ steps.login-ecr.outputs.registry }}/${{ env.APP_NAME }}:${{ env.IMAGE_TAG }}

      - name: Debug Rendered Task Definition
        run: cat ${{ steps.task-def.outputs.task-definition }}

      - name: Deploy to Amazon ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v2
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ env.APP_NAME }}
          cluster: ${{ env.ECS_CLUSTER }}
          wait-for-service-stability: true
