name: ECS Deploy (practice)

on:
  push:
    branches:
      - v2

env:
  AWS_REGION: "ap-northeast-1"
  AWS_ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}
  AWS_ROLE_NAME: ${{ secrets.AWS_ROLE_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: "arn:aws:iam::${{ env.AWS_ACCOUNT_ID }}:role/${{ env.AWS_ROLE_NAME }}"
          aws-region: ${{ env.AWS_REGION }}

      - name: Identity Check
        run: |
          aws sts get-caller-identity > /dev/null && echo "AWS Login OK"
